version: "2.4"

services:
  image-db-cli:
    image: ghcr.io/pharmbio/imagedb-cli
    restart: always
    container_name: imagedb-cli
    command: python3 /app/image-monitor.py
    cpus: 2
    mem_limit: 2g
    environment:
      # CONF_FILE: settings_dev_local.json
      CONF_FILE: ${CONF_FILE?You need to specify env CONF_FILE, e.g. settings_dev_local.json, settings_prod.json}
    volumes:
      - ${APPROOT}:/app
      - ${SHARE_MIKRO}:/share/mikro
      - ${SHARE_MIKRO2}:/share/mikro2
      - ${SHARE_IMAGEDB}:/share/imagedb
      - ${SHARE_EXTERNAL}:/share/data/external-datasets
